#!/bin/sh
# The purpose of this script is to continually run and to
# create a new generated sheet when new raw input is detected

trap "echo 'Exiting Watcher'; exit;" SIGINT SIGTERM
last_update=''
while true; do
	most_recent="`ls -t raw_transactions | head -1`"
	if [ "$most_recent" != "$last_update" ]; then
		last_update="$most_recent"
		date
		echo "Updating last_update: '$last_update'"
		echo "Running run script"
		./run >output.txt 2>&1
		if [ "$?" -ne 0 ]; then
			echo "run script failed"
			exit 1
		fi
	fi
	sleep 60
done
