#!/bin/sh
# The purpose of this script is to continually run and to
# create a new generated sheet when new raw input is detected

trap "echo 'Exiting Watcher'; exit;" SIGINT SIGTERM
last_update=''
while true; do
	most_recent="`ls -t raw_transactions | head -1`"
	if [ "$most_recent" != "$last_update" ]; then
		last_update="$most_recent"
		date
		echo "Updating last_update: '$last_update'"
		echo "Running run script"
		./run >output.txt 2>&1
		error_code="$?"
		if [ "$error_code" -eq 2 ]; then # if auth token is expired
			echo "Removing authorized user file"
			./rm_auth_user.sh # remove authorized user file
			echo "Re-Running run script"
			./run >output.txt 2>&1
			error_code="$?"
		fi
		echo "Done"
		if [ "$error_code" -ne 0 ]; then
			echo "run script failed"
			exit 1
		fi
	fi
	sleep 2
done
